#!/usr/bin/env python3

from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from reportlab.lib.colors import black, blue, grey, darkblue, darkgreen, red
from reportlab.lib import colors
import datetime

def create_exchange_pages_spec():
    # Create PDF document
    filename = "Exchange_Pages_Specification.pdf"
    doc = SimpleDocTemplate(filename, pagesize=A4, 
                          topMargin=1*inch, bottomMargin=1*inch,
                          leftMargin=1*inch, rightMargin=1*inch)
    
    # Get sample style sheet and create custom styles
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Title'],
        fontSize=24,
        alignment=TA_CENTER,
        spaceAfter=30,
        textColor=red
    )
    
    header_style = ParagraphStyle(
        'CustomHeader',
        parent=styles['Heading1'],
        fontSize=16,
        spaceAfter=12,
        spaceBefore=20,
        textColor=red
    )
    
    subheader_style = ParagraphStyle(
        'CustomSubHeader',
        parent=styles['Heading2'],
        fontSize=14,
        spaceAfter=8,
        spaceBefore=12,
        textColor=black
    )
    
    body_style = ParagraphStyle(
        'CustomBody',
        parent=styles['Normal'],
        fontSize=11,
        spaceAfter=6,
        alignment=TA_JUSTIFY,
        leftIndent=0,
        rightIndent=0
    )
    
    highlight_style = ParagraphStyle(
        'Highlight',
        parent=styles['Normal'],
        fontSize=12,
        spaceAfter=8,
        alignment=TA_CENTER,
        textColor=red,
        fontName='Helvetica-Bold'
    )
    
    # Build content
    content = []
    
    # Title Page
    content.append(Paragraph("BITCOIN APPS EXCHANGE PAGES", title_style))
    content.append(Spacer(1, 0.3*inch))
    content.append(Paragraph(".ft Token Trading Platform for Bitcoin Apps Ecosystem", styles['Heading1']))
    content.append(Spacer(1, 0.2*inch))
    content.append(Paragraph("Revenue Generation & App Token Distribution Model", styles['Heading2']))
    content.append(Spacer(1, 0.5*inch))
    content.append(Paragraph("Bitcoin Corporation Ltd", body_style))
    content.append(Spacer(1, 0.2*inch))
    content.append(Paragraph(f"Version 1.0 - {datetime.datetime.now().strftime('%B %d, %Y')}", styles['Normal']))
    content.append(Spacer(1, 1*inch))
    
    # Executive Summary Box
    content.append(Paragraph("EXECUTIVE SUMMARY", highlight_style))
    content.append(Spacer(1, 0.2*inch))
    content.append(Paragraph("""
    Each Bitcoin App features an integrated Exchange Page (/exchange) where users can trade .ft tokens created from 
    Work NFTs within that specific app. Exchange trading generates revenue through transaction fees, premium features, 
    and market-making services, with all proceeds distributed as dividends to the app's specific token holders 
    ($bWriter, $bVideo, $bMusic, etc.).
    """, body_style))
    content.append(PageBreak())
    
    # What are Exchange Pages
    content.append(Paragraph("WHAT ARE EXCHANGE PAGES?", header_style))
    
    content.append(Paragraph("App-Specific Token Trading Platforms", subheader_style))
    content.append(Paragraph("""
    Each Bitcoin App includes a dedicated Exchange Page where .ft tokens created from that app's Work NFTs are traded. 
    Bitcoin Writer trades dividend tokens from document NFTs, Bitcoin Video exchanges revenue shares from video NFTs, 
    creating specialized financial markets for each content type.
    """, body_style))
    
    content.append(Paragraph("Financial Infrastructure for Creators", subheader_style))
    content.append(Paragraph("""
    Exchange Pages provide sophisticated financial tools for creator economy participants. Investors can build portfolios 
    of creator tokens, creators can raise capital through token sales, and secondary markets enable liquidity for 
    revenue-sharing investments in digital work products.
    """, body_style))
    
    content.append(Paragraph("Revenue Distribution to App Token Holders", subheader_style))
    content.append(Paragraph("""
    All revenue generated by Exchange Page activities (trading fees, premium features, market data subscriptions) is 
    distributed as dividends to holders of the app's specific token. Exchange revenue from Bitcoin Writer goes to $bWriter 
    holders, Bitcoin Video exchange revenue to $bVideo holders, creating investment exposure to financial trading activity.
    """, body_style))
    
    # Exchange Features by App Type
    content.append(Paragraph("EXCHANGE FEATURES BY APPLICATION", header_style))
    
    content.append(Paragraph("Specialized Trading Interfaces", subheader_style))
    
    app_exchange_data = [
        ["Feature", "Bitcoin Writer", "Bitcoin Video", "Bitcoin Music"],
        ["Token Types", "Document revenue shares, licensing", "Video royalties, distribution rights", "Music royalties, performance rights"],
        ["Trading Pairs", ".ft/BSV, .ft/USD, .ft/.ft", "Video tokens vs. BSV/USD", "Music tokens vs. BSV/USD"],
        ["Order Types", "Market, Limit, Stop-Loss, DCA", "Standard + streaming-based orders", "Standard + performance-based orders"],
        ["Analytics", "Document performance metrics", "View counts, engagement data", "Play counts, streaming revenue"],
        ["Price Discovery", "Revenue-based valuations", "Audience metrics influence", "Popularity and royalty-based"],
        ["Liquidity Tools", "Automated market makers", "Creator liquidity pools", "Genre-specific liquidity"],
        ["Risk Management", "Creator diversification tools", "Content category risk metrics", "Artist and genre risk analysis"]
    ]
    
    app_exchange_table = Table(app_exchange_data, colWidths=[1.5*inch, 1.5*inch, 1.5*inch, 1.5*inch])
    app_exchange_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.red),
        ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTNAME', (0,1), (-1,-1), 'Helvetica'),
        ('FONTSIZE', (0,0), (-1,-1), 9),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
        ('TOPPADDING', (0,0), (-1,-1), 8),
        ('LEFTPADDING', (0,0), (-1,-1), 4),
        ('RIGHTPADDING', (0,0), (-1,-1), 4),
        ('GRID', (0,0), (-1,-1), 1, colors.black)
    ]))
    content.append(app_exchange_table)
    content.append(Spacer(1, 0.3*inch))
    
    # Trading Mechanisms
    content.append(Paragraph("ADVANCED TRADING MECHANISMS", header_style))
    
    content.append(Paragraph("Automated Market Makers (AMMs)", subheader_style))
    content.append(Paragraph("""
    Each app's Exchange Page features automated market makers providing liquidity for .ft token trading. AMMs use 
    dynamic pricing based on token supply, demand, and underlying Work NFT performance metrics. Liquidity providers 
    earn fees from trading activity, creating additional revenue streams for token ecosystems.
    """, body_style))
    
    content.append(Paragraph("Performance-Based Pricing", subheader_style))
    content.append(Paragraph("""
    Token prices reflect real-time performance of underlying Work NFTs. Document download rates influence writer token 
    prices, video view counts affect video token valuations, music streaming data drives music token pricing. This 
    creates efficient markets where token values correlate with actual content performance.
    """, body_style))
    
    content.append(Paragraph("Cross-App Arbitrage Opportunities", subheader_style))
    content.append(Paragraph("""
    Sophisticated traders can identify arbitrage opportunities across different app exchanges. Popular creators working 
    across multiple apps may have different token valuations, creating trading opportunities. The $bEx central exchange 
    enables portfolio strategies and cross-app arbitrage execution.
    """, body_style))
    
    content.append(PageBreak())
    
    # Revenue Model
    content.append(Paragraph("REVENUE MODEL & TOKEN DISTRIBUTION", header_style))
    
    content.append(Paragraph("Exchange Page Revenue Sources", subheader_style))
    
    exchange_revenue_data = [
        ["Revenue Source", "Rate/Fee", "Description"],
        ["Trading Commission", "0.25% per trade", "Fee on all .ft token transactions"],
        ["Premium Trading Tools", "$14.99/month", "Advanced charts, alerts, analytics"],
        ["Market Making Service", "0.1% of volume", "Automated liquidity provision fee"],
        ["Institutional API", "$99/month", "High-frequency trading access"],
        ["Price Data Feeds", "$4.99/month", "Real-time market data subscriptions"],
        ["Portfolio Analytics", "$9.99/month", "Advanced portfolio tracking and insights"],
        ["Copy Trading Platform", "10% of profits", "Follow successful trader strategies"]
    ]
    
    exchange_revenue_table = Table(exchange_revenue_data, colWidths=[2.2*inch, 1.5*inch, 2.8*inch])
    exchange_revenue_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.darkgreen),
        ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTNAME', (0,1), (-1,-1), 'Helvetica'),
        ('FONTSIZE', (0,0), (-1,-1), 10),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('BOTTOMPADDING', (0,0), (-1,-1), 10),
        ('TOPPADDING', (0,0), (-1,-1), 8),
        ('LEFTPADDING', (0,0), (-1,-1), 6),
        ('RIGHTPADDING', (0,0), (-1,-1), 6),
        ('GRID', (0,0), (-1,-1), 1, colors.black)
    ]))
    content.append(exchange_revenue_table)
    content.append(Spacer(1, 0.3*inch))
    
    content.append(Paragraph("Revenue Distribution to App Tokens", subheader_style))
    content.append(Paragraph("""
    100% of Exchange Page revenue is distributed quarterly as dividends to holders of the app's specific token. 
    Trading activity from Bitcoin Writer .ft tokens generates dividends for $bWriter holders, Bitcoin Video trading 
    benefits $bVideo holders, creating direct correlation between financial market activity and token holder returns.
    """, body_style))
    
    # Financial Projections
    content.append(Paragraph("FINANCIAL PROJECTIONS BY APP", header_style))
    
    content.append(Paragraph("5-Year Trading Volume & Revenue Projections (Per App)", subheader_style))
    
    trading_financial_data = [
        ["Metric", "Year 1", "Year 2", "Year 3", "Year 4", "Year 5"],
        ["Active Traders", "200", "1.5K", "8K", "30K", "100K"],
        ["Monthly Trading Volume", "$100K", "$1.5M", "$15M", "$85M", "$400M"],
        ["Average Trade Size", "$500", "$1,000", "$1,875", "$2,833", "$4,000"],
        ["Monthly Transactions", "200", "1.5K", "8K", "30K", "100K"],
        ["Exchange Revenue", "$3K", "$45K", "$450K", "$2.55M", "$12M"],
        ["Token Dividend Pool", "$3K", "$45K", "$450K", "$2.55M", "$12M"],
        ["Revenue Per Token (1M supply)", "$0.003", "$0.045", "$0.45", "$2.55", "$12.00"]
    ]
    
    trading_financial_table = Table(trading_financial_data, colWidths=[1.8*inch, 0.8*inch, 0.8*inch, 0.8*inch, 0.8*inch, 0.8*inch])
    trading_financial_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.red),
        ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTNAME', (0,1), (-1,-1), 'Helvetica'),
        ('FONTSIZE', (0,0), (-1,-1), 9),
        ('ALIGN', (1,0), (-1,-1), 'RIGHT'),
        ('ALIGN', (0,0), (0,-1), 'LEFT'),
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
        ('TOPPADDING', (0,0), (-1,-1), 8),
        ('LEFTPADDING', (0,0), (-1,-1), 6),
        ('RIGHTPADDING', (0,0), (-1,-1), 6),
        ('GRID', (0,0), (-1,-1), 1, colors.black)
    ]))
    content.append(trading_financial_table)
    content.append(Spacer(1, 0.3*inch))
    
    content.append(Paragraph("Ecosystem Trading Volume Scaling", subheader_style))
    content.append(Paragraph("""
    With 15+ Bitcoin Apps each generating $12M annually in exchange revenue by Year 5, the total ecosystem trading revenue 
    exceeds $180M. Network effects accelerate growth as successful tokens in one app drive interest and trading activity 
    across the entire ecosystem.
    """, body_style))
    
    # Technical Implementation
    content.append(Paragraph("TECHNICAL IMPLEMENTATION", header_style))
    
    content.append(Paragraph("Exchange Page Architecture", subheader_style))
    
    tech_exchange_data = [
        ["Component", "Function", "Implementation"],
        ["Order Book Engine", "Match buy and sell orders", "High-performance matching engine with priority queues"],
        ["Smart Contract Integration", "Execute trades and settlements", "BSV scripts for atomic swaps and escrow"],
        ["Price Oracle System", "Real-time pricing and market data", "Work NFT performance feeds and trading data"],
        ["Liquidity Pools", "Automated market making", "Dynamic pricing algorithms with fee distribution"],
        ["Portfolio Management", "Track positions and performance", "Real-time portfolio analytics and risk metrics"],
        ["API Gateway", "External trading integrations", "RESTful and WebSocket APIs for institutional access"],
        ["Revenue Distribution", "Quarterly dividend payments", "Automated distribution to app token holders"]
    ]
    
    tech_exchange_table = Table(tech_exchange_data, colWidths=[1.5*inch, 2.5*inch, 2.5*inch])
    tech_exchange_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.lightgrey),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTNAME', (0,1), (-1,-1), 'Helvetica'),
        ('FONTSIZE', (0,0), (-1,-1), 10),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('BOTTOMPADDING', (0,0), (-1,-1), 10),
        ('TOPPADDING', (0,0), (-1,-1), 8),
        ('LEFTPADDING', (0,0), (-1,-1), 6),
        ('RIGHTPADDING', (0,0), (-1,-1), 6),
        ('GRID', (0,0), (-1,-1), 1, colors.black)
    ]))
    content.append(tech_exchange_table)
    
    content.append(PageBreak())
    
    # User Experience & Trading Flow
    content.append(Paragraph("USER EXPERIENCE & TRADING FLOW", header_style))
    
    content.append(Paragraph("Creator-to-Investor Pipeline", subheader_style))
    
    trading_flow_steps = [
        "Creator produces content and converts to Work NFT with revenue terms",
        "Creator mints .ft tokens from Work NFT, setting dividend percentages",
        "Tokens are listed on app's Exchange Page for initial sale",
        "Investors purchase tokens to gain exposure to creator revenue streams",
        "Secondary trading begins with sophisticated order types and analytics",
        "Work NFT performance drives token demand and price discovery",
        "Trading fees accumulate in app token dividend pool",
        "Quarterly distribution of exchange revenue to app token holders"
    ]
    
    for i, step in enumerate(trading_flow_steps, 1):
        content.append(Paragraph(f"{i}. {step}", body_style))
    
    content.append(Spacer(1, 0.3*inch))
    content.append(Paragraph("Advanced Trading Features", subheader_style))
    
    trading_features = [
        "Real-time market depth and order book visualization",
        "Performance-based alerts tied to underlying Work NFT metrics",
        "Dollar-cost averaging for systematic creator investment strategies", 
        "Stop-loss orders to manage downside risk on creator tokens",
        "Portfolio rebalancing tools for diversified creator exposure",
        "Social trading features to follow successful creator investors",
        "Cross-app arbitrage detection and execution tools",
        "Institutional-grade API access for algorithmic trading strategies"
    ]
    
    for feature in trading_features:
        content.append(Paragraph(f"• {feature}", body_style))
    
    # Investment Opportunity
    content.append(Paragraph("INVESTMENT OPPORTUNITY & MARKET ANALYSIS", header_style))
    
    content.append(Paragraph("Creator Finance Market Opportunity", subheader_style))
    content.append(Paragraph("""
    The creator finance market is nascent but rapidly growing, with platforms like Patreon generating $1B+ annually. 
    Exchange Pages capture the next evolution: liquid secondary markets for creator investments. First-mover advantage 
    in creator finance infrastructure creates sustainable competitive moats and significant revenue opportunities.
    """, body_style))
    
    content.append(Paragraph("Token Investment Thesis", subheader_style))
    content.append(Paragraph("""
    App tokens provide leveraged exposure to both creator success AND trading activity. As creators build audiences 
    and generate revenue, their tokens become more valuable. Simultaneously, increased trading volume generates 
    additional exchange revenue distributed to app token holders, creating multiple revenue streams for investors.
    """, body_style))
    
    content.append(Paragraph("Ecosystem Network Effects", subheader_style))
    content.append(Paragraph("""
    Exchange Pages create powerful network effects across the Bitcoin Apps ecosystem. Successful trading strategies 
    in one app attract users to others, cross-app portfolio construction drives ecosystem-wide trading volume, and 
    the $bEx central exchange enables sophisticated investment strategies across all app tokens.
    """, body_style))
    
    content.append(Spacer(1, 0.4*inch))
    content.append(Paragraph("Regulatory Compliance & Risk Management", subheader_style))
    content.append(Paragraph("""
    All .ft tokens are treated as securities with appropriate investor protections and regulatory compliance. 
    Exchange Pages implement comprehensive KYC/AML procedures, maintain proper books and records, and provide 
    necessary reporting for regulatory authorities. Risk management tools help investors understand and manage 
    exposure to creator economy volatility.
    """, body_style))
    
    content.append(Spacer(1, 0.3*inch))
    content.append(Paragraph("Combined Market and Exchange Revenue", subheader_style))
    content.append(Paragraph("""
    Exchange Pages complement Market Pages to create comprehensive revenue streams for app tokens. By Year 5, 
    each app generates $18.75M from marketplace activity and $12M from exchange trading, totaling $30.75M annually 
    per app. Across 15+ apps, this represents $460M+ in annual ecosystem revenue distributed to app token holders.
    """, body_style))
    
    # Build PDF
    doc.build(content)
    return filename

if __name__ == "__main__":
    try:
        filename = create_exchange_pages_spec()
        print(f"Exchange Pages specification created successfully: {filename}")
    except Exception as e:
        print(f"Error creating specification: {e}")