#!/usr/bin/env python3

from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from reportlab.lib.colors import black, blue, grey, darkblue, darkgreen, orange
from reportlab.lib import colors
import datetime

def create_market_pages_spec():
    # Create PDF document
    filename = "Market_Pages_Specification.pdf"
    doc = SimpleDocTemplate(filename, pagesize=A4, 
                          topMargin=1*inch, bottomMargin=1*inch,
                          leftMargin=1*inch, rightMargin=1*inch)
    
    # Get sample style sheet and create custom styles
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Title'],
        fontSize=24,
        alignment=TA_CENTER,
        spaceAfter=30,
        textColor=orange
    )
    
    header_style = ParagraphStyle(
        'CustomHeader',
        parent=styles['Heading1'],
        fontSize=16,
        spaceAfter=12,
        spaceBefore=20,
        textColor=orange
    )
    
    subheader_style = ParagraphStyle(
        'CustomSubHeader',
        parent=styles['Heading2'],
        fontSize=14,
        spaceAfter=8,
        spaceBefore=12,
        textColor=black
    )
    
    body_style = ParagraphStyle(
        'CustomBody',
        parent=styles['Normal'],
        fontSize=11,
        spaceAfter=6,
        alignment=TA_JUSTIFY,
        leftIndent=0,
        rightIndent=0
    )
    
    highlight_style = ParagraphStyle(
        'Highlight',
        parent=styles['Normal'],
        fontSize=12,
        spaceAfter=8,
        alignment=TA_CENTER,
        textColor=orange,
        fontName='Helvetica-Bold'
    )
    
    # Build content
    content = []
    
    # Title Page
    content.append(Paragraph("BITCOIN APPS MARKET PAGES", title_style))
    content.append(Spacer(1, 0.3*inch))
    content.append(Paragraph("NFT Trading Marketplace for Bitcoin Apps Ecosystem", styles['Heading1']))
    content.append(Spacer(1, 0.2*inch))
    content.append(Paragraph("Revenue Generation & App Token Distribution Model", styles['Heading2']))
    content.append(Spacer(1, 0.5*inch))
    content.append(Paragraph("Bitcoin Corporation Ltd", body_style))
    content.append(Spacer(1, 0.2*inch))
    content.append(Paragraph(f"Version 1.0 - {datetime.datetime.now().strftime('%B %d, %Y')}", styles['Normal']))
    content.append(Spacer(1, 1*inch))
    
    # Executive Summary Box
    content.append(Paragraph("EXECUTIVE SUMMARY", highlight_style))
    content.append(Spacer(1, 0.2*inch))
    content.append(Paragraph("""
    Each Bitcoin App (Writer, Video, Music, etc.) features an integrated Market Page where users can buy, sell, 
    and trade Work NFTs created within that specific app. Market transactions generate revenue through listing fees, 
    sales commissions, and premium features, with all proceeds distributed as dividends to the app's specific token holders 
    ($bWriter, $bVideo, $bMusic, etc.).
    """, body_style))
    content.append(PageBreak())
    
    # What are Market Pages
    content.append(Paragraph("WHAT ARE MARKET PAGES?", header_style))
    
    content.append(Paragraph("App-Specific NFT Marketplaces", subheader_style))
    content.append(Paragraph("""
    Each Bitcoin App includes a dedicated Market Page (/market) where Work NFTs created within that app are traded. 
    Bitcoin Writer markets document NFTs, Bitcoin Video trades video NFTs, Bitcoin Music exchanges music NFTs, 
    creating specialized marketplaces optimized for each content type.
    """, body_style))
    
    content.append(Paragraph("Integrated Creation & Commerce", subheader_style))
    content.append(Paragraph("""
    Market Pages seamlessly integrate with the app's creation tools. Users can create content, convert it to Work NFTs, 
    and immediately list it for sale without leaving the app environment. This integrated workflow maximizes creator 
    monetization opportunities and marketplace liquidity.
    """, body_style))
    
    content.append(Paragraph("Revenue Distribution to Token Holders", subheader_style))
    content.append(Paragraph("""
    All revenue generated by Market Page activities (listing fees, sales commissions, premium features) is distributed 
    as dividends to holders of the app's specific token. Bitcoin Writer market revenue goes to $bWriter holders, 
    Bitcoin Video revenue to $bVideo holders, creating direct investment exposure to app usage and success.
    """, body_style))
    
    # Market Page Features by App Type
    content.append(Paragraph("MARKET FEATURES BY APPLICATION", header_style))
    
    content.append(Paragraph("Bitcoin Writer Document Market", subheader_style))
    app_features_data = [
        ["Feature", "Bitcoin Writer", "Bitcoin Video", "Bitcoin Music"],
        ["Content Type", "Documents, Reports, Articles", "Videos, Films, Tutorials", "Music, Audio, Podcasts"],
        ["Preview System", "Document thumbnails & excerpts", "Video previews & trailers", "Audio samples & previews"],
        ["Licensing Options", "Usage rights, commercial licenses", "Distribution rights, streaming", "Performance rights, sync licenses"],
        ["Metadata", "Word count, topic tags, format", "Duration, quality, genre", "BPM, key, genre, instruments"],
        ["Pricing Models", "One-time, subscription, per-page", "Rental, purchase, streaming", "Per-play, album, sync rights"],
        ["Discovery Tools", "Search by topic, author, format", "Search by genre, duration, rating", "Search by genre, mood, tempo"]
    ]
    
    app_features_table = Table(app_features_data, colWidths=[1.5*inch, 1.5*inch, 1.5*inch, 1.5*inch])
    app_features_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.orange),
        ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTNAME', (0,1), (-1,-1), 'Helvetica'),
        ('FONTSIZE', (0,0), (-1,-1), 9),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
        ('TOPPADDING', (0,0), (-1,-1), 8),
        ('LEFTPADDING', (0,0), (-1,-1), 4),
        ('RIGHTPADDING', (0,0), (-1,-1), 4),
        ('GRID', (0,0), (-1,-1), 1, colors.black)
    ]))
    content.append(app_features_table)
    content.append(Spacer(1, 0.3*inch))
    
    # Revenue Model
    content.append(Paragraph("REVENUE MODEL & TOKEN DISTRIBUTION", header_style))
    
    content.append(Paragraph("Market Page Revenue Sources", subheader_style))
    
    revenue_sources_data = [
        ["Revenue Source", "Rate/Fee", "Description"],
        ["NFT Listing Fee", "$2.99 per listing", "Fee to list Work NFT on marketplace"],
        ["Sales Commission", "5% of sale price", "Commission on successful NFT sales"],
        ["Featured Listing", "$9.99 per week", "Premium placement in marketplace"],
        ["Bulk Listing Package", "$19.99 for 20 listings", "Discounted listing for volume creators"],
        ["Market Analytics", "$4.99/month", "Advanced sales data and market insights"],
        ["Creator Verification", "$49.99 one-time", "Verified creator badge and premium features"]
    ]
    
    revenue_table = Table(revenue_sources_data, colWidths=[2.2*inch, 1.5*inch, 2.8*inch])
    revenue_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.darkgreen),
        ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTNAME', (0,1), (-1,-1), 'Helvetica'),
        ('FONTSIZE', (0,0), (-1,-1), 10),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('BOTTOMPADDING', (0,0), (-1,-1), 10),
        ('TOPPADDING', (0,0), (-1,-1), 8),
        ('LEFTPADDING', (0,0), (-1,-1), 6),
        ('RIGHTPADDING', (0,0), (-1,-1), 6),
        ('GRID', (0,0), (-1,-1), 1, colors.black)
    ]))
    content.append(revenue_table)
    content.append(Spacer(1, 0.3*inch))
    
    content.append(Paragraph("Revenue Distribution to App Tokens", subheader_style))
    content.append(Paragraph("""
    100% of Market Page revenue is distributed monthly as dividends to holders of the app's specific token. 
    Bitcoin Writer market revenue goes to $bWriter holders, Bitcoin Video to $bVideo holders, Bitcoin Music to $bMusic holders. 
    This creates direct correlation between app usage, creator success, and token holder returns.
    """, body_style))
    
    content.append(PageBreak())
    
    # Financial Projections
    content.append(Paragraph("FINANCIAL PROJECTIONS BY APP", header_style))
    
    content.append(Paragraph("5-Year Revenue Projections (Per App)", subheader_style))
    
    financial_data = [
        ["Metric", "Year 1", "Year 2", "Year 3", "Year 4", "Year 5"],
        ["Active Creators", "500", "2.5K", "10K", "35K", "100K"],
        ["Monthly NFT Listings", "2K", "15K", "75K", "300K", "1M"],
        ["Monthly Sales Volume", "$50K", "$500K", "$3.5M", "$18M", "$75M"],
        ["Market Page Revenue", "$15K", "$125K", "$875K", "$4.5M", "$18.75M"],
        ["Token Dividend Pool", "$15K", "$125K", "$875K", "$4.5M", "$18.75M"],
        ["Revenue Per Token (1M supply)", "$0.015", "$0.125", "$0.875", "$4.50", "$18.75"]
    ]
    
    financial_table = Table(financial_data, colWidths=[1.8*inch, 0.8*inch, 0.8*inch, 0.8*inch, 0.8*inch, 0.8*inch])
    financial_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.orange),
        ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTNAME', (0,1), (-1,-1), 'Helvetica'),
        ('FONTSIZE', (0,0), (-1,-1), 9),
        ('ALIGN', (1,0), (-1,-1), 'RIGHT'),
        ('ALIGN', (0,0), (0,-1), 'LEFT'),
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
        ('TOPPADDING', (0,0), (-1,-1), 8),
        ('LEFTPADDING', (0,0), (-1,-1), 6),
        ('RIGHTPADDING', (0,0), (-1,-1), 6),
        ('GRID', (0,0), (-1,-1), 1, colors.black)
    ]))
    content.append(financial_table)
    content.append(Spacer(1, 0.3*inch))
    
    content.append(Paragraph("Cross-App Market Dynamics", subheader_style))
    content.append(Paragraph("""
    With 15+ Bitcoin Apps each generating $18.75M annually by Year 5, the total ecosystem market revenue exceeds $280M. 
    Early app tokens benefit from first-mover advantage, while later apps leverage established marketplace infrastructure 
    and user base for accelerated growth.
    """, body_style))
    
    # Technical Implementation
    content.append(Paragraph("TECHNICAL IMPLEMENTATION", header_style))
    
    content.append(Paragraph("Market Page Architecture", subheader_style))
    
    tech_components_data = [
        ["Component", "Function", "Implementation"],
        ["NFT Catalog", "Browse and discover Work NFTs", "Searchable database with metadata filtering"],
        ["Smart Contracts", "Handle escrow and ownership transfer", "BSV scripts for secure NFT trading"],
        ["Payment Processing", "Handle fiat and crypto payments", "HandCash integration with multi-currency support"],
        ["Revenue Tracking", "Monitor all market transactions", "Real-time revenue calculation and reporting"],
        ["Dividend Distribution", "Distribute revenue to token holders", "Automated monthly payments to token wallets"],
        ["Creator Tools", "Listing management and analytics", "Dashboard for creators to manage their NFTs"]
    ]
    
    tech_table = Table(tech_components_data, colWidths=[1.5*inch, 2.5*inch, 2.5*inch])
    tech_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.lightgrey),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTNAME', (0,1), (-1,-1), 'Helvetica'),
        ('FONTSIZE', (0,0), (-1,-1), 10),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('BOTTOMPADDING', (0,0), (-1,-1), 10),
        ('TOPPADDING', (0,0), (-1,-1), 8),
        ('LEFTPADDING', (0,0), (-1,-1), 6),
        ('RIGHTPADDING', (0,0), (-1,-1), 6),
        ('GRID', (0,0), (-1,-1), 1, colors.black)
    ]))
    content.append(tech_table)
    content.append(Spacer(1, 0.3*inch))
    
    content.append(Paragraph("User Experience Flow", subheader_style))
    
    ux_flow_steps = [
        "Creator produces content using Bitcoin App tools",
        "Creator converts work to NFT with embedded payment terms",
        "Creator lists NFT on app's Market Page with pricing and licensing",
        "Buyers discover NFTs through search, categories, and recommendations",
        "Purchase transactions handled through smart contracts and HandCash",
        "Market fees automatically calculated and added to app dividend pool",
        "Monthly dividend distribution to app token holders based on holdings",
        "Secondary sales generate additional revenue for continued distributions"
    ]
    
    for i, step in enumerate(ux_flow_steps, 1):
        content.append(Paragraph(f"{i}. {step}", body_style))
    
    content.append(PageBreak())
    
    # Investment Opportunity
    content.append(Paragraph("INVESTMENT OPPORTUNITY & MARKET ANALYSIS", header_style))
    
    content.append(Paragraph("Creator Economy Market Size", subheader_style))
    content.append(Paragraph("""
    The global creator economy exceeds $104 billion annually, with NFT marketplaces capturing $25 billion in trading volume. 
    App-specific marketplaces offer superior user experience and targeted discovery, positioning Bitcoin Apps to capture 
    significant market share in specialized content verticals.
    """, body_style))
    
    content.append(Paragraph("Competitive Advantages", subheader_style))
    market_advantages = [
        "Integrated creation and commerce within single app environment",
        "Content-type optimized discovery and preview systems", 
        "Direct revenue sharing with app token holders creates investment incentive",
        "Seamless HandCash payment integration for superior user experience",
        "Cross-app ecosystem effects increase overall platform value",
        "Bitcoin blockchain provides permanent, immutable ownership records"
    ]
    
    for advantage in market_advantages:
        content.append(Paragraph(f"• {advantage}", body_style))
    
    content.append(Spacer(1, 0.3*inch))
    content.append(Paragraph("Token Investment Strategy", subheader_style))
    content.append(Paragraph("""
    App tokens ($bWriter, $bVideo, $bMusic, etc.) provide direct exposure to marketplace revenue growth. Early token acquisition 
    in high-potential apps offers significant upside as creator adoption and trading volume increase. Portfolio diversification 
    across multiple app tokens reduces risk while maintaining exposure to ecosystem growth.
    """, body_style))
    
    content.append(Paragraph("Implementation Timeline", subheader_style))
    
    timeline_data = [
        ["Phase", "Timeline", "Deliverables", "Revenue Target"],
        ["Beta Launch", "Months 1-3", "Basic marketplace for 3 apps", "$50K monthly"],
        ["Feature Expansion", "Months 4-8", "Advanced tools for all 15 apps", "$250K monthly"],
        ["Market Optimization", "Months 9-18", "AI-powered discovery, mobile apps", "$1M monthly"],
        ["Global Scaling", "Years 2-3", "International expansion, fiat onramps", "$5M monthly"],
        ["Market Leadership", "Years 4-5", "Enterprise features, institutional adoption", "$25M monthly"]
    ]
    
    timeline_table = Table(timeline_data, colWidths=[1.2*inch, 1.2*inch, 2.4*inch, 1.2*inch])
    timeline_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.orange),
        ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTNAME', (0,1), (-1,-1), 'Helvetica'),
        ('FONTSIZE', (0,0), (-1,-1), 9),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
        ('TOPPADDING', (0,0), (-1,-1), 8),
        ('LEFTPADDING', (0,0), (-1,-1), 6),
        ('RIGHTPADDING', (0,0), (-1,-1), 6),
        ('GRID', (0,0), (-1,-1), 1, colors.black)
    ]))
    content.append(timeline_table)
    
    content.append(Spacer(1, 0.4*inch))
    content.append(Paragraph("Ecosystem Integration & Network Effects", subheader_style))
    content.append(Paragraph("""
    Market Pages create powerful network effects across the Bitcoin Apps ecosystem. Successful creators in one app 
    drive adoption in others, cross-app collaborations generate multi-app revenue streams, and the $bEx central exchange 
    enables sophisticated portfolio strategies across all app tokens. By Year 5, we project $280M+ in annual ecosystem 
    marketplace revenue distributed to app token holders.
    """, body_style))
    
    # Build PDF
    doc.build(content)
    return filename

if __name__ == "__main__":
    try:
        filename = create_market_pages_spec()
        print(f"Market Pages specification created successfully: {filename}")
    except Exception as e:
        print(f"Error creating specification: {e}")