#!/usr/bin/env python3

from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from reportlab.lib.colors import black, blue, grey, darkblue, darkgreen, purple
from reportlab.lib import colors
import datetime

def create_token_container_spec():
    # Create PDF document
    filename = "Token_Container_FT_Spec.pdf"
    doc = SimpleDocTemplate(filename, pagesize=A4, 
                          topMargin=1*inch, bottomMargin=1*inch,
                          leftMargin=1*inch, rightMargin=1*inch)
    
    # Get sample style sheet and create custom styles
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Title'],
        fontSize=24,
        alignment=TA_CENTER,
        spaceAfter=30,
        textColor=purple
    )
    
    header_style = ParagraphStyle(
        'CustomHeader',
        parent=styles['Heading1'],
        fontSize=16,
        spaceAfter=12,
        spaceBefore=20,
        textColor=purple
    )
    
    subheader_style = ParagraphStyle(
        'CustomSubHeader',
        parent=styles['Heading2'],
        fontSize=14,
        spaceAfter=8,
        spaceBefore=12,
        textColor=black
    )
    
    body_style = ParagraphStyle(
        'CustomBody',
        parent=styles['Normal'],
        fontSize=11,
        spaceAfter=6,
        alignment=TA_JUSTIFY,
        leftIndent=0,
        rightIndent=0
    )
    
    highlight_style = ParagraphStyle(
        'Highlight',
        parent=styles['Normal'],
        fontSize=12,
        spaceAfter=8,
        alignment=TA_CENTER,
        textColor=purple,
        fontName='Helvetica-Bold'
    )
    
    # Build content
    content = []
    
    # Title Page
    content.append(Paragraph(".ft TOKEN CONTAINERS", title_style))
    content.append(Spacer(1, 0.3*inch))
    content.append(Paragraph("Dividend & Royalty Token Minting Platform", styles['Heading1']))
    content.append(Spacer(1, 0.2*inch))
    content.append(Paragraph("Financial Tokenization Specification & Investment Model", styles['Heading2']))
    content.append(Spacer(1, 0.5*inch))
    content.append(Paragraph("Bitcoin Corporation Ltd", body_style))
    content.append(Spacer(1, 0.2*inch))
    content.append(Paragraph(f"Version 1.0 - {datetime.datetime.now().strftime('%B %d, %Y')}", styles['Normal']))
    content.append(Spacer(1, 1*inch))
    
    # Executive Summary Box
    content.append(Paragraph("EXECUTIVE SUMMARY", highlight_style))
    content.append(Spacer(1, 0.2*inch))
    content.append(Paragraph("""
    .ft Token Containers enable creators to mint dividend-bearing shares and royalty tokens from their Work NFTs, 
    creating sophisticated investment vehicles and secondary markets. Investors can purchase tokens representing 
    fractional ownership in revenue streams from digital work products, enabling new forms of creator financing 
    and investor returns.
    """, body_style))
    content.append(PageBreak())
    
    # What are .ft Token Containers
    content.append(Paragraph("WHAT ARE .ft TOKEN CONTAINERS?", header_style))
    
    content.append(Paragraph("The Concept", subheader_style))
    content.append(Paragraph("""
    .ft Token Containers allow creators to "financialize" their Work NFTs by minting tokens that represent ownership 
    stakes in the revenue streams generated by their digital work. These tokens function as securities, providing 
    investors with returns based on the performance and usage of the underlying work products.
    """, body_style))
    
    content.append(Paragraph("Token Types & Structures", subheader_style))
    content.append(Paragraph("""
    Creators can mint multiple types of tokens from a single Work NFT: dividend shares that distribute revenue 
    proportionally, royalty tokens that capture specific usage fees, performance tokens that pay based on metrics, 
    and governance tokens that provide voting rights on work modifications or licensing terms.
    """, body_style))
    
    content.append(Paragraph("Investment Vehicle Creation", subheader_style))
    content.append(Paragraph("""
    .ft containers transform individual work products into tradeable investment opportunities. A successful spreadsheet 
    model, popular document template, or valuable dataset can be tokenized to raise capital for the creator while 
    providing investors with exposure to digital work performance.
    """, body_style))
    
    # Value Creation Mechanism
    content.append(Paragraph("VALUE CREATION MECHANISM", header_style))
    
    content.append(Paragraph("Creator Capital Access", subheader_style))
    content.append(Paragraph("""
    Creators can raise capital by selling tokens representing future revenue from their work. This enables pre-revenue 
    financing for development projects, expansion capital for successful products, and liquidity for creators who want 
    to realize value from their work without losing all future upside.
    """, body_style))
    
    content.append(Paragraph("Investor Revenue Opportunities", subheader_style))
    content.append(Paragraph("""
    Investors gain access to new asset class of digital work revenue streams. Returns are tied directly to work 
    performance: usage fees, subscription revenue, licensing income, and derivative work royalties. This creates 
    transparent, performance-based investment opportunities with clear underlying value drivers.
    """, body_style))
    
    content.append(Paragraph("Market Liquidity & Discovery", subheader_style))
    content.append(Paragraph("""
    Token containers create liquid secondary markets for creator investments. Investors can trade tokens based on 
    work performance, market conditions, and portfolio needs. This liquidity attracts more capital to high-quality 
    creators and enables efficient price discovery for digital work assets.
    """, body_style))
    
    # Investment Opportunity
    content.append(Paragraph("PLATFORM INVESTMENT OPPORTUNITY", header_style))
    
    content.append(Paragraph("Creator Economy Financialization", subheader_style))
    content.append(Paragraph("""
    The global creator economy exceeds $100 billion annually, but most creators lack access to sophisticated financing 
    options. .ft Token Containers capture this opportunity by providing infrastructure for creator securitization, 
    enabling new forms of creative financing and investment.
    """, body_style))
    
    content.append(Paragraph("Transaction Volume Scaling", subheader_style))
    content.append(Paragraph("""
    Platform revenue grows with token trading volume, secondary market transactions, and new token issuances. As 
    successful work products generate returns for early investors, market confidence and participation increase, 
    driving exponential growth in transaction volume and platform revenue.
    """, body_style))
    
    content.append(Paragraph("Financial Infrastructure Moat", subheader_style))
    content.append(Paragraph("""
    Building comprehensive tokenization infrastructure requires significant technical expertise, regulatory compliance, 
    and marketplace development. First-mover advantage in this space creates sustainable competitive moats through 
    network effects, creator relationships, and investor trust.
    """, body_style))
    
    content.append(PageBreak())
    
    # Technical Architecture
    content.append(Paragraph("TECHNICAL ARCHITECTURE", title_style))
    content.append(Spacer(1, 0.3*inch))
    
    content.append(Paragraph("Token Container Structure", header_style))
    
    # Technical components
    tech_components_data = [
        ["Component", "Function", "Implementation"],
        ["Revenue Oracle", "Tracks Work NFT performance & earnings", "Blockchain-based data feed from NFT contracts"],
        ["Token Smart Contract", "Manages token supply, distribution, voting", "BSV script with governance mechanisms"],
        ["Distribution Engine", "Calculates and distributes token payments", "Automated revenue splitting algorithm"],
        ["Trading Interface", "Enables token buying, selling, transfer", "DEX integration with order book"],
        ["Governance System", "Manages token holder voting and decisions", "Weighted voting based on token holdings"],
        ["Compliance Framework", "Ensures securities law compliance", "KYC/AML integration and reporting tools"]
    ]
    
    tech_table = Table(tech_components_data, colWidths=[1.5*inch, 2.5*inch, 2.5*inch])
    tech_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.purple),
        ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTNAME', (0,1), (-1,-1), 'Helvetica'),
        ('FONTSIZE', (0,0), (-1,-1), 10),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('BOTTOMPADDING', (0,0), (-1,-1), 10),
        ('TOPPADDING', (0,0), (-1,-1), 8),
        ('LEFTPADDING', (0,0), (-1,-1), 6),
        ('RIGHTPADDING', (0,0), (-1,-1), 6),
        ('GRID', (0,0), (-1,-1), 1, colors.black)
    ]))
    content.append(tech_table)
    content.append(Spacer(1, 0.3*inch))
    
    content.append(Paragraph("Token Minting Process", subheader_style))
    
    # Minting process steps
    minting_steps = [
        "Creator selects Work NFT for tokenization",
        "Define token structure: dividend %, supply, governance rights",
        "Set fundraising target and token price",
        "Platform validates Work NFT performance and revenue history",
        "Smart contract is created with specified terms",
        "Tokens are minted and made available for investment",
        "Revenue from Work NFT is automatically distributed to token holders",
        "Secondary market enables token trading and price discovery"
    ]
    
    for i, step in enumerate(minting_steps, 1):
        content.append(Paragraph(f"{i}. {step}", body_style))
    
    content.append(Spacer(1, 0.3*inch))
    content.append(Paragraph("Token Types & Use Cases", subheader_style))
    
    # Token types table
    token_types_data = [
        ["Token Type", "Structure", "Use Case", "Investor Returns"],
        ["Dividend Shares", "Profit sharing", "Revenue-generating work", "% of ongoing revenue"],
        ["Royalty Tokens", "Usage-based", "High-traffic content", "Fixed fee per use"],
        ["Growth Tokens", "Performance-based", "Scaling projects", "Returns tied to metrics"],
        ["Governance Tokens", "Voting rights", "Collaborative work", "Control + revenue share"],
        ["Hybrid Tokens", "Mixed structure", "Complex projects", "Multiple return streams"]
    ]
    
    token_types_table = Table(token_types_data, colWidths=[1.3*inch, 1.3*inch, 1.6*inch, 1.6*inch])
    token_types_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.lightgrey),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTNAME', (0,1), (-1,-1), 'Helvetica'),
        ('FONTSIZE', (0,0), (-1,-1), 9),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
        ('TOPPADDING', (0,0), (-1,-1), 8),
        ('LEFTPADDING', (0,0), (-1,-1), 4),
        ('RIGHTPADDING', (0,0), (-1,-1), 4),
        ('GRID', (0,0), (-1,-1), 1, colors.black)
    ]))
    content.append(token_types_table)
    
    content.append(PageBreak())
    
    # Revenue Model & Financial Projections
    content.append(Paragraph("REVENUE MODEL & FINANCIAL PROJECTIONS", header_style))
    
    content.append(Paragraph("Platform Revenue Streams", subheader_style))
    
    # Platform revenue
    platform_revenue_data = [
        ["Revenue Source", "Rate/Fee", "Description"],
        ["Token Minting Fee", "$99 per token", "One-time fee to create .ft container"],
        ["Trading Commission", "1.5% per trade", "Fee on secondary market transactions"],
        ["Management Fee", "0.5% annually", "Fee on assets under management"],
        ["Premium Features", "$19.99/month", "Advanced analytics, governance tools"],
        ["Institutional Suite", "$499/month", "Enterprise-grade compliance & reporting"],
        ["White-label Licensing", "$10K setup + 2%", "Custom tokenization platforms"]
    ]
    
    platform_rev_table = Table(platform_revenue_data, colWidths=[2*inch, 1.5*inch, 3*inch])
    platform_rev_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.darkgreen),
        ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTNAME', (0,1), (-1,-1), 'Helvetica'),
        ('FONTSIZE', (0,0), (-1,-1), 10),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('BOTTOMPADDING', (0,0), (-1,-1), 10),
        ('TOPPADDING', (0,0), (-1,-1), 8),
        ('LEFTPADDING', (0,0), (-1,-1), 6),
        ('RIGHTPADDING', (0,0), (-1,-1), 6),
        ('GRID', (0,0), (-1,-1), 1, colors.black)
    ]))
    content.append(platform_rev_table)
    content.append(Spacer(1, 0.3*inch))
    
    content.append(Paragraph("Investment Examples & Returns", subheader_style))
    
    # Investment examples
    investment_examples = [
        "Successful Spreadsheet Model: 1,000 tokens @ $10 each = $10K raised, 15% annual dividends",
        "Popular Document Template: 5,000 tokens @ $5 each = $25K raised, $0.02 per use royalty",
        "High-Traffic Dataset: 2,500 tokens @ $20 each = $50K raised, 25% revenue sharing",
        "Collaborative Design Tool: 10,000 tokens @ $2 each = $20K raised, governance + 10% dividends",
        "Premium Research Report: 500 tokens @ $100 each = $50K raised, 40% revenue sharing"
    ]
    
    for example in investment_examples:
        content.append(Paragraph(f"• {example}", body_style))
    
    content.append(Spacer(1, 0.3*inch))
    content.append(Paragraph("5-Year Financial Projections", subheader_style))
    
    # 5-year projections
    financial_ft_data = [
        ["Metric", "Year 1", "Year 2", "Year 3", "Year 4", "Year 5"],
        ["Active Token Containers", "100", "1K", "5K", "20K", "75K"],
        ["Total Tokens Minted", "50K", "500K", "3M", "15M", "75M"],
        ["Assets Under Management", "$500K", "$15M", "$150M", "$1.2B", "$8B"],
        ["Trading Volume (Monthly)", "$50K", "$1M", "$25M", "$200M", "$1.5B"],
        ["Platform Revenue", "$250K", "$3.5M", "$45M", "$275M", "$1.2B"],
        ["Investor Distributions", "$100K", "$2.5M", "$35M", "$240M", "$1.6B"]
    ]
    
    financial_ft_table = Table(financial_ft_data, colWidths=[1.8*inch, 0.8*inch, 0.8*inch, 0.8*inch, 0.8*inch, 0.8*inch])
    financial_ft_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.purple),
        ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTNAME', (0,1), (-1,-1), 'Helvetica'),
        ('FONTSIZE', (0,0), (-1,-1), 9),
        ('ALIGN', (1,0), (-1,-1), 'RIGHT'),
        ('ALIGN', (0,0), (0,-1), 'LEFT'),
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
        ('TOPPADDING', (0,0), (-1,-1), 8),
        ('LEFTPADDING', (0,0), (-1,-1), 6),
        ('RIGHTPADDING', (0,0), (-1,-1), 6),
        ('GRID', (0,0), (-1,-1), 1, colors.black)
    ]))
    content.append(financial_ft_table)
    
    content.append(PageBreak())
    
    # Implementation Strategy & Roadmap
    content.append(Paragraph("IMPLEMENTATION STRATEGY & ROADMAP", header_style))
    
    content.append(Paragraph("Phase 1: Infrastructure Development (Months 1-8)", subheader_style))
    content.append(Paragraph("""
    • Build core tokenization smart contract infrastructure
    • Develop revenue tracking and distribution systems
    • Create basic trading interface and secondary market
    • Target: 50 token containers, $250K in assets under management
    """, body_style))
    
    content.append(Paragraph("Phase 2: Market Development (Months 9-18)", subheader_style))
    content.append(Paragraph("""
    • Launch comprehensive marketplace for token discovery
    • Implement advanced governance and voting mechanisms
    • Add institutional-grade compliance and reporting tools
    • Target: 500 token containers, $10M assets under management
    """, body_style))
    
    content.append(Paragraph("Phase 3: Scale & Sophistication (Months 19-36)", subheader_style))
    content.append(Paragraph("""
    • Develop complex financial instruments and derivatives
    • Launch white-label tokenization platform for enterprises
    • Integrate with traditional financial markets and custody
    • Target: 5,000 token containers, $150M assets under management
    """, body_style))
    
    content.append(Paragraph("Phase 4: Market Leadership (Years 4-5)", subheader_style))
    content.append(Paragraph("""
    • Establish platform as standard for creator tokenization
    • Expand globally with localized compliance frameworks
    • Develop API partnerships with major financial institutions
    • Target: 75,000 token containers, $8B assets under management
    """, body_style))
    
    content.append(Paragraph("Regulatory Compliance Strategy", header_style))
    
    content.append(Paragraph("Securities Law Compliance", subheader_style))
    content.append(Paragraph("""
    All .ft tokens are treated as securities and offered only to accredited investors or through appropriate regulatory 
    exemptions. The platform maintains comprehensive KYC/AML procedures and provides necessary reporting to comply 
    with applicable securities regulations.
    """, body_style))
    
    content.append(Paragraph("International Expansion", subheader_style))
    content.append(Paragraph("""
    Platform expansion follows regulatory approval in each jurisdiction, starting with crypto-friendly regions and 
    gradually expanding to major markets as regulatory frameworks develop. Local partnerships ensure compliance with 
    regional securities and financial services regulations.
    """, body_style))
    
    content.append(Spacer(1, 0.4*inch))
    content.append(Paragraph("Competitive Positioning & Market Impact", subheader_style))
    content.append(Paragraph("""
    .ft Token Containers create an entirely new asset class by financializing digital work products. By Year 5, 
    we project $8 billion in assets under management, generating $1.2 billion in annual platform revenue while 
    distributing $1.6 billion annually to investors in creator tokens.
    """, body_style))
    
    content.append(Spacer(1, 0.3*inch))
    content.append(Paragraph("Ecosystem Integration", subheader_style))
    content.append(Paragraph("""
    .ft Token Containers build upon Save to Chain and Work NFT Containerization infrastructure, creating a 
    comprehensive creator economy platform. This integrated approach provides multiple revenue streams while 
    creating powerful network effects that accelerate adoption across all product categories.
    """, body_style))
    
    # Build PDF
    doc.build(content)
    return filename

if __name__ == "__main__":
    try:
        filename = create_token_container_spec()
        print(f".ft Token Container specification created successfully: {filename}")
    except Exception as e:
        print(f"Error creating specification: {e}")